# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/windows-qt6.yml
      - /gitlab-templates/linux-qt6.yml

variables:
    GIT_SUBMODULE_STRATEGY: recursive

      

