language: cpp

matrix:
  include:
    - dist: xenial
      compiler: clang
      before_install:
          - sudo add-apt-repository -y ppa:$PPA
          - sudo apt-get -qy update
      install:
          - sudo apt-get -qy install qt${QT}quickcontrols  qt${QT}svg  qt${QT}quickcontrols2  qt${QT}webengine  qt${QT}multimedia  qt${QT}imageformats  qt${QT}graphicaleffects  qt${QT}declarative  qt${QT}base qt${QT}translations  qt${QT}tools  qt${QT}xmlpatterns mesa-common-dev libglu1-mesa-dev freeglut3-dev
      env:
          - QT=512 BREW=@ex PPA=beineri/opt-qt-5.12.3-xenial QMAKESPEC=linux-clang QT_SELECT=qt5 QMAKE_CC=clang-7.0 QMAKE_CXX=clang++-7.0 QMAKE_CXXFLAGS="-stdlib=libc++" QMAKE_LFLAGS="-stdlib=libc++"
          - MATRIX_EVAL="CC=clang-7.0 && CXX=clang++-7.0"
      before_script:
        - . /opt/qt$QT/bin/qt$QT-env.sh

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      before_install:
          - sudo add-apt-repository -y ppa:$PPA
          - sudo apt-get -qy update
      install:
          - sudo apt-get -qy install qt${QT}quickcontrols  qt${QT}svg  qt${QT}quickcontrols2  qt${QT}webengine  qt${QT}multimedia  qt${QT}imageformats  qt${QT}graphicaleffects  qt${QT}declarative  qt${QT}base qt${QT}translations  qt${QT}tools  qt${QT}xmlpatterns mesa-common-dev libglu1-mesa-dev freeglut3-dev
          -  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
      env:
          - QT=512 BREW=@ex PPA=beineri/opt-qt-5.12.3-xenial QMAKESPEC=linux-g++ QT_SELECT=qt5 QMAKE_CC=gcc-7  QMAKE_CXX=g++-7 QMAKE_CXXFLAGS="" QMAKE_LFLAGS=""
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_script:
        - . /opt/qt$QT/bin/qt$QT-env.sh

    - os: osx
      osx_image: xcode10
      before_install:
          - travis_wait 30 brew update
      before_script:
            - sudo Xvfb :99 -ac -screen 0 1024x768x8 &
      install:
            - brew install cppcheck
            - brew install qt5
            - brew link --force qt
      env:
          - QMAKESPEC=macx-clang QMAKE_CXXFLAGS="" QMAKE_LFLAGS=""

before_install:
  - eval "${MATRIX_EVAL}"
  - git submodule update --init --remote --recursive
  - g++ --version
  - sudo updatedb
  - locate libc++.so

script:
  - mkdir -p "$TRAVIS_BUILD_DIR-build"
  - pushd "$TRAVIS_BUILD_DIR-build"
  - lrelease "$TRAVIS_BUILD_DIR/client/client.pro"
  - lrelease "$TRAVIS_BUILD_DIR/server/server.pro"
  - qmake -r -Wall -Wlogic -Wparser CONFIG+=debug CONFIG+=TESTS -spec $QMAKESPEC QCONFIG+="c++11" QMAKE_CXXFLAGS="$QMAKE_CXXFLAGS" QMAKE_LFLAGS="$QMAKE_LFLAGS" "$TRAVIS_BUILD_DIR"
  - make -j2
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then (xvfb-run make -s -j2 check -C "$TRAVIS_BUILD_DIR-build") fi
  - if [ "$TRAVIS_OS_NAME" = osx   ] ; then (make -s -j2 check -C "$TRAVIS_BUILD_DIR-build") fi
  - popd
